# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PandaTalk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PandaTalk

  # For Syntax sugar
  pod 'Then'

  # For AutoLayout
  pod 'SnapKit'

  # For RxCommunity
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxFlow'
  pod 'RxOptional'
  pod 'RxController'
  pod 'RxDataSources', '~> 4.0'
  pod 'RxBinding'
  pod 'RxKeyboard'

  # For Debug
  pod 'FLEX', :configurations => ['Debug']
  pod 'Gedatsu', configuration: %w(Debug)

  # For Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'FirebaseUI'
  pod 'GoogleSignIn'

  # For RxFirebase
  pod 'RxFirebase/Firestore'
  pod 'RxFirebase/RemoteConfig'
  pod 'RxFirebase/Database'
  pod 'RxFirebase/Storage'
  pod 'RxFirebase/Auth'
  pod 'RxFirebase/Functions'

  # For SkeletonView
  pod "SkeletonView"

  # For MDC
  pod 'MaterialComponents/TextFields'
  pod 'MaterialComponents/Buttons'
  pod 'MaterialComponents/Dialogs'
  pod 'MaterialComponents/ActivityIndicator'
  pod 'MaterialComponents/ProgressView'

  target 'PandaTalkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PandaTalkUITests' do
    # Pods for testing
  end

end
